name: Docker CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Hub'a Giris Yap
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Kodu Cek (checkout)
        uses: actions/checkout@v3

      - name: Docker Image Build Et
        run: docker build -t my-app:latest .

      - name: Docker Container Test Et
        run: docker run my-app python --version